#!/usr/bin/python
# Scipt for collating information en-mass from .flagstats files generated by samtools.
# Nicholas Gleadall - nick.gleadall@googlemail.com - 15/12/2014

#print "hello world"

#----------------------------------------------------------------------------------------

import re
import os
import sys

#----------------------------------------------------------------------------------------

nReads = ""
nMapped = ""
nDuplicate = ""
AvgIns = ""

nMapn = 0
nDup = 0

#----------------------------------------------------------------------------------------

print "Sample\tReads (n)\tReads Mapped (%)\tDuplicate Reads (%)\tAverage Insert Size"

#----------------------------------------------------------------------------------------

indir = sys.argv[1]


for file in os.listdir(indir):
	if not file.endswith(".bam.flagstat"):
		continue

	samplename = re.sub(r'(.*).bam.*', r"\1", file)
	infile = open(indir + file, "rU")

	for i, line in enumerate(infile):
		#print line
		if i == 0:
			nline = line.split(" ")
			nReads = nline[0]

		if i == 2:
			line = line.strip("\n")
			nline = re.sub(r'(.*)\((.*):.*', r'\2', line)
			nMapped = nline

			nline = line.split(" ")
			nMapn = int(nline[0])

		if i == 1:
			nline = line.split(" ")
			nDup = nline[0].strip(" ")
			nDuplicate = int(nDup)/int(nReads)*100

# section specific to clinical genetics analysis methods - includes average insert
# size files within analysis.
	AvgIns = "N/A"
	isizefile_name = indir + samplename + ".bam.isize"

	if (  os.path.isfile( isizefile_name )):

		isizefile = open( isizefile_name )
		for i, line in enumerate(isizefile):
			if i == 7:
				nline = line.split("\t")
				AvgIns = nline[0]


	print "%s\t%s\t%s\t%.2f%%\t%s" % (samplename, nReads, nMapped, nDuplicate, AvgIns)
